# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_enderecobr_wrappers", use_symbols = TRUE, package_name = "enderecobr")

#' @usage NULL
#' @useDynLib enderecobr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Return string `"Hello world!"` to R.
#' @export
bairro_rs <- function(bairros) .Call(wrap__bairro_rs, bairros)

#' a.
#' @export
bairro_rs_dani <- function(bairros) .Call(wrap__bairro_rs_dani, bairros)


# nolint end
